### ISSUE TITLE
Image Name SEO

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#157]
after resizing image with
<pre>< img src="img/cmsimage.php/300x300x1/{ THUMB_HASH }.{ THUMB_EXT }" / ></pre>
the file name ist gone and replaced with a long number. a seo/ search engine optimization guy tells us that the real name would be much better.

any remarks to this?

**Comment by q23** [comment]
should we implement a switch and pull it?

**Comment by slackero** [comment]
SEO guys tell a lot when the day is long. Describe the image and it's fine for the search engine to index it. The alt-attribute is the most important thing and it is a required attribute too.

The file name is gone since ever by the way.

But if you like to have a file name — fake it there. 
`<img src="img/cmsimage.php/300x300x1/{THUMB_HASH}.{THUMB_EXT}/{IMAGE_NAME}" alt="" />`

Remember the config setting `$phpwcms['cmsimage_redirect'] = false;`
