### ISSUE TITLE
Warning nach PHP Mailer Update

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#196]
Nachdem ich den PHP Mailler auf den neuesten Stand brachte (komplettes Verzeichnis **phpmailer** ausgetauscht) wird beim versenden einer Nachricht eine Warnig ausgegeben.

![mailer](https://cloud.githubusercontent.com/assets/2964678/21601865/24b772b8-d18f-11e6-80bc-94893ed5d632.jpg)

Verwendete Version: phpwcms 1.8.4 (2016/07/22, r543)
Nachdem ich den alten Mailer zurück spielte wird kein Fehler mehr ausgegeben.

**Comment by slackero** [comment]
Darauf achten, dass in Shared Umgebungen PHP als Apache Servermodul oftmals aus Sicherheitsgründen funktionsbeschränkt ist, z.B. Shell-Zugriffe beschnitten oder ganz verboten werden.

Be ware that shared hosting accounts often limit PHP functionality when used as Apache server module instead of CGI/FastCGI/FPM. Proof that first.
