### ISSUE TITLE
Problem with pathes after Update when cms is in Root Directory

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#320]
Hi,

after updating phpwcms to the newest version
- phpwcms 1.9.30
- phpwcms 1.9.31_dev

it is not possible to login in BE until this setting in inc.config.php
$phpwcms['root'] = ''; //default: ''
is changed to this
$phpwcms['root'] = '/'; //default: ''

After this BE Login is able again. But still Problems in FE.
- All Subpages with double starting slash in URL (e.g. domain.tld//subpages)
- us of {TEMPLATE} breaks on every subpage because of missing starting slash (e.g. template/yourfont.css instead of /template/yourfrontend.css is a huge difference)
- pathes of images and included modules all breaks

![Unbenannt](https://user-images.githubusercontent.com/2988261/135890725-31a57e3b-bc0a-4522-b3b2-680e5d6c5d94.jpg)

For us it looks like the system is working in subdirectory but not on root.
Tested on Hetzner, 1&1 and own servers.

Looking forward,

q23.robert

**Comment by uwe367** [comment]
I can´t confirm this.
Last 2 Days i updatet 8 installations to 1.9.31, the oldest was a 1.9.0 from 2018, and all are running very well in BE And FE with the default settings like `$phpwcms['root'] = ''; //default: ''`.  Backendlogin works as expected, editing content and creating of new content works as expected and Frontend displays what it should.
All installations are running on the servers from all-inkl and on my localhost on XAMPP.

Maybe there´s a problem with the settings in .htaccess in your installation?
For me it sounds like this because you have to add a slash in the settings.....

Or something was going wrong in the update-process....
That are some only ideas....

**Comment by slackero** [comment]
Before I dive deeper testing, maybe check all recent changes regarding cookies and base href. I guess your problem lay somewhere there. Delete cookies for the old installations. My local test system runs well in document root.

**Comment by q23** [comment]
Thx and solved. Since 1.9.x is better to clear cookies after update
