### ISSUE TITLE
Mail function could not be initialized. (php-Version 8.3)

### ISSUE THREAD

**Issue by fhksmso** [slackero/phpwcms#357]
Sending a request via the contact form no longer works after updating to version 1.10-dev.

Fehlermeldung: Mail-Funktion konnte nicht initialisiert werden.
Error message: Mail function could not be initialized.

![email_einstellungen](https://github.com/slackero/phpwcms/assets/47750914/fc00d29b-19d3-4dcb-9bd0-ccdfad9f4ac6)

Example:
https://fewo-loritz.de/anfrageformular.html

Otherwise everything will work again.

**Comment by slackero** [comment]
I cannot confirm this, maybe your provider has some restrictions regarding sending this way. Check the mail logs and find out more about the reason.

Otherwise try to use SMTP – PHP mail often is blocked. Check that the sender email fits the domain, SPF records are correct and so on∞

It seems your site is hosted by IONOS, I guess they reject this because of stricter content policy rules.

**Comment by slackero** [comment]
It seems you have solved the problem, I close this issue
