### ISSUE TITLE
Call to undefined method Erusev\Parsedown\Parsedown::text() 

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#360]
latest dev-version (1.10.3-dev (2024/07/06, r554)

PHP Fatal error:  Uncaught Error: Call to undefined method Erusev\Parsedown\Parsedown::text() in website/include/inc_front/content/cnt32.article.inc.php:154
Stack trace:
#0 /website/include/inc_front/content.article.inc.php(615): include()
#1 /website/include/inc_front/content.func.inc.php(711): include_once('/var/www/client...')
#2 /vwebsite/index.php(69): require('/var/www/client...')
#3 {main}

Solved in
/web/include/inc_front/content/cnt32.article.inc.php:Z153
by replacing
init_markdown();
with

                        if(!isset($phpwcms['parsedown_class'])) {
                            require_once PHPWCMS_ROOT.'/include/inc_ext/parsedown/Parsedown.php';
                            require_once PHPWCMS_ROOT.'/include/inc_ext/parsedown-extra/ParsedownExtra.php';
                            $phpwcms['parsedown_class'] = new ParsedownExtra();
                        }

**Comment by slackero** [comment]
It seems you have a problem with your vendor directory. The Parsedown classes are not available since long time under `/include/inc_ext/parsedown/`and `/include/inc_ext/parsedown-extra/`.
Check your [`/include/vendor/`](https://github.com/slackero/phpwcms/tree/master/include/vendor) directory. [`/include/vendor/erusev/`](https://github.com/slackero/phpwcms/tree/master/include/vendor/erusev) should be there. If not update your installation.
